name: cicd workflow

on:
  push:
    branches:
      ['main','develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: build project
        run: echo build complete!

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy app
        run: echo deploy develop complete!