name: cicd workflow

on:
  push:
    branches:
      ['main','develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build project
        run: echo build complete!

  develop:
    runs-on: ubuntu-latest
    needs: build    
    if: github.ref == 'refs/heads/develop'
    environment:
      name: develop
    env:
      CONTAINER_NAME: quality-ai-api-dev-container      
    steps:
      - name: Deploy app development 
        run: echo "env=$CONTAINER_NAME" 

  production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    env:
      CONTAINER_NAME: quality-ai-api-container   
    steps:
      - name: Deploy app production
        run: echo "env=$CONTAINER_NAME" 